//! Runtime generation of the tinyproxy allowlist.
//!
//! The list is written from `settings.proxy.allow` (merged across global
//! and workspace) directly — no hidden base layer. [`DEFAULT_ALLOW_ENTRIES`]
//! lives here only as the seed for a freshly-created global
//! `settings.toml`; once the file is on disk every rule behaves like any
//! other user-authored one.
//!
//! The generated file is placed under XDG cache with the invoker's PID
//! embedded so concurrent invocations don't race on the same filename.
//! tinyproxy bind-mounts it read-only.

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use directories::ProjectDirs;

/// Bundled default allow-list, seeded into a fresh global `settings.toml`.
///
/// Curated to avoid hosts that expose destructive write endpoints — most
/// visibly `api.github.com` and `uploads.github.com`, where a stolen PAT
/// in the workspace could delete repos or upload arbitrary release
/// assets via the REST API. `github.com` itself stays for `git clone`
/// and release artifact fetches. Package registries are included for
/// install paths; users with publish credentials on those same hosts
/// should be aware of the residual risk.
pub const DEFAULT_ALLOW_ENTRIES: &[&str] = &[
    // agent-container host broker (fresh AWS creds, MCP proxy)
    r"^host\.docker\.internal$",
    // Claude / Anthropic
    r"^api\.anthropic\.com$",
    r"^statsig\.anthropic\.com$",
    r"^platform\.claude\.com$",
    r"^claude\.ai$",
    r"^console\.anthropic\.com$",
    // OpenAI / ChatGPT (Codex with ChatGPT subscription auth)
    r"^chatgpt\.com$",
    r"^api\.openai\.com$",
    r"^auth\.openai\.com$",
    // AWS Bedrock (only used when CLAUDE_CODE_USE_BEDROCK is set)
    r"^bedrock-runtime\.[a-z0-9-]+\.amazonaws\.com$",
    r"^bedrock\.[a-z0-9-]+\.amazonaws\.com$",
    // Rust toolchain
    r"^crates\.io$",
    r"^static\.crates\.io$",
    r"^index\.crates\.io$",
    r"^static\.rust-lang\.org$",
    r"^sh\.rustup\.rs$",
    // Node / npm
    r"^registry\.npmjs\.org$",
    r"^registry\.yarnpkg\.com$",
    // Python
    r"^pypi\.org$",
    r"^files\.pythonhosted\.org$",
    // Go modules
    r"^proxy\.golang\.org$",
    r"^sum\.golang\.org$",
    // GitHub read-path only (clone + release artifacts).
    r"^github\.com$",
    r"^codeload\.github\.com$",
    r"^raw\.githubusercontent\.com$",
    r"^objects\.githubusercontent\.com$",
    r"^release-assets\.githubusercontent\.com$",
    // Debian / Ubuntu apt repos (container base image updates)
    r"^deb\.debian\.org$",
    r"^security\.debian\.org$",
    r"^archive\.ubuntu\.com$",
    r"^security\.ubuntu\.com$",
    r"^ports\.ubuntu\.com$",
    // Alpine package repos
    r"^dl-cdn\.alpinelinux\.org$",
];

pub fn default_allow_entries() -> Vec<String> {
    DEFAULT_ALLOW_ENTRIES
        .iter()
        .map(|s| (*s).to_string())
        .collect()
}

/// Serialise `allow` into tinyproxy's expected format — one pattern per
/// line, blank/whitespace entries dropped — and write the result to
/// `dest`.
pub fn generate(allow: &[String], dest: &PathBuf) -> Result<()> {
    let mut out = String::from(
        "# generated by agent-container — edit proxy rules via `agent-container config`\n",
    );
    for pat in allow {
        let trimmed = pat.trim();
        if trimmed.is_empty() {
            continue;
        }
        out.push_str(trimmed);
        out.push('\n');
    }

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(dest, out)
        .with_context(|| format!("failed to write allowlist to {}", dest.display()))?;
    Ok(())
}

/// Per-process path under XDG cache so simultaneous invocations (e.g. a
/// dev running `agent-container run` alongside `agent-container shell`)
/// get their own file and don't clobber each other.
pub fn cache_path_for(pid: u32) -> Result<PathBuf> {
    let dirs = ProjectDirs::from("", "", "agent-container")
        .context("failed to resolve XDG project directories")?;
    Ok(dirs
        .cache_dir()
        .join(format!("proxy-allowlist.{pid}.txt")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_entries_are_nonempty_and_well_formed() {
        let entries = default_allow_entries();
        assert!(!entries.is_empty(), "bundled defaults should not be empty");
        for e in &entries {
            assert!(!e.trim().is_empty());
            assert!(!e.starts_with('#'));
        }
        // Anthropic API is the headline entry — if it drops out of the
        // bundled list, agent-container itself stops working. The
        // bundled rules are ERE regex so the dot is backslash-escaped.
        assert!(
            entries.iter().any(|e| e.contains("anthropic")),
            "expected an anthropic rule in the bundled defaults",
        );
    }

    #[test]
    fn defaults_omit_destructive_github_endpoints() {
        // Guard against regression. See the doc comment on
        // DEFAULT_ALLOW_ENTRIES for the rationale.
        let entries = default_allow_entries();
        for banned in ["api.github.com", "uploads.github.com"] {
            assert!(
                entries.iter().all(|e| !e.contains(banned)),
                "{banned} must stay off the bundled defaults",
            );
        }
    }

    #[test]
    fn generate_writes_patterns_one_per_line() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(&vec!["^a\\.com$".into(), "^b\\.com$".into()], &dest).unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(rules, vec!["^a\\.com$", "^b\\.com$"]);
    }

    #[test]
    fn generate_skips_blank_entries() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(&vec!["".into(), "   ".into(), "^x$".into()], &dest).unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(rules, vec!["^x$"]);
    }

    #[test]
    fn generate_produces_file_even_with_no_entries() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(&[], &dest).unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert!(rules.is_empty());
        // Header comment is always present so tinyproxy has something
        // well-formed to read.
        assert!(got.starts_with('#'));
    }
}
