//! Runtime generation of the tinyproxy allowlist.
//!
//! The list is written from `settings.proxy.allow` (merged across global
//! and workspace) directly — no hidden base layer. The bundled
//! [`DEFAULT_ALLOWLIST_TEXT`] lives here only as the seed for a
//! freshly-created global `settings.toml`; once the file is on disk
//! every rule behaves like any other user-authored one.
//!
//! The generated file is placed under XDG cache with the invoker's PID
//! embedded so concurrent invocations don't race on the same filename.
//! tinyproxy bind-mounts it read-only.
//!
//! [`DEFAULT_ALLOWLIST_TEXT`]: fn@default_allow_entries

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use directories::ProjectDirs;

/// Verbatim contents of `docker/proxy/allowlist.txt`, baked into the
/// binary at compile time. Acts as the seed for `Settings::load_global`
/// when no global `settings.toml` exists yet — after the first save,
/// the on-disk file is authoritative and this constant is no longer
/// consulted.
pub const DEFAULT_ALLOWLIST_TEXT: &str =
    include_str!("../docker/proxy/allowlist.txt");

/// Parse [`DEFAULT_ALLOWLIST_TEXT`] into the individual allow patterns
/// (skipping blanks and `#` comments), preserving declaration order so
/// the materialised defaults read the same as the source file.
pub fn default_allow_entries() -> Vec<String> {
    DEFAULT_ALLOWLIST_TEXT
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(String::from)
        .collect()
}

/// Serialise `allow` into tinyproxy's expected format — one pattern per
/// line, blank/whitespace entries dropped — and write the result to
/// `dest`.
pub fn generate(allow: &[String], dest: &PathBuf) -> Result<()> {
    let mut out = String::from(
        "# generated by agent-container — edit proxy rules via `agent-container config`\n",
    );
    for pat in allow {
        let trimmed = pat.trim();
        if trimmed.is_empty() {
            continue;
        }
        out.push_str(trimmed);
        out.push('\n');
    }

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(dest, out)
        .with_context(|| format!("failed to write allowlist to {}", dest.display()))?;
    Ok(())
}

/// Per-process path under XDG cache so simultaneous invocations (e.g. a
/// dev running `agent-container run` alongside `agent-container shell`)
/// get their own file and don't clobber each other.
pub fn cache_path_for(pid: u32) -> Result<PathBuf> {
    let dirs = ProjectDirs::from("", "", "agent-container")
        .context("failed to resolve XDG project directories")?;
    Ok(dirs
        .cache_dir()
        .join(format!("proxy-allowlist.{pid}.txt")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_entries_are_nonempty_and_comment_free() {
        let entries = default_allow_entries();
        assert!(!entries.is_empty(), "bundled defaults should not be empty");
        for e in &entries {
            assert!(!e.trim().is_empty());
            assert!(!e.starts_with('#'));
        }
        // Anthropic API is the headline entry — if it drops out of the
        // bundled list, agent-container itself stops working. The
        // bundled rules are ERE regex so the dot is backslash-escaped.
        assert!(
            entries.iter().any(|e| e.contains("anthropic")),
            "expected an anthropic rule in the bundled defaults",
        );
    }

    #[test]
    fn generate_writes_patterns_one_per_line() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(
            &vec!["^a\\.com$".into(), "^b\\.com$".into()],
            &dest,
        )
        .unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(rules, vec!["^a\\.com$", "^b\\.com$"]);
    }

    #[test]
    fn generate_skips_blank_entries() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(
            &vec!["".into(), "   ".into(), "^x$".into()],
            &dest,
        )
        .unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(rules, vec!["^x$"]);
    }

    #[test]
    fn generate_produces_file_even_with_no_entries() {
        let dir = tempfile::tempdir().unwrap();
        let dest = dir.path().join("out.txt");
        generate(&[], &dest).unwrap();
        let got = fs::read_to_string(&dest).unwrap();
        let rules: Vec<&str> = got
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert!(rules.is_empty());
        // Header comment is always present so tinyproxy has something
        // well-formed to read.
        assert!(got.starts_with('#'));
    }
}
